sass:
  style: compressed

remote_theme: showzeng/Minimalism

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: Infinity Render
name: Infinity Render
# description: Minimalism is a jekyll theme for minimalist

show_excerpt: true

github: https://github.com/MORIZHIJIANDX
rss: false

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
  
  
